version: "2"
services:
  db:
    image: "postgres:11"
    #container_name: "test_postgres"
    environment:
      POSTGRES_USER: ${ENV_POSTGRES_USR}
      POSTGRES_PASSWORD: ${ENV_POSTGRES_PWD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - ${ENV_POSTGRES_SERVER_PORT}
    volumes:
      - /var/lib/postgresql/data
      #- kakfa_db_instance:/var/lib/postgresql/data
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.2.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${ENV_KAFKA_HOST}
      KAFKA_CREATE_TOPICS: ${ENV_KAFKA_TOPIC}
      KAFKA_ZOOKEEPER_CONNECT: ${ENV_KAFKA_ZOOKEEPER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#volumes:
#  kakfa_db_instance:
